<?php include("login_headerscript.php"); ?>
<?php include("admin_functions.php"); ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 
<title>Safety Assessment</title>
</head>
<body>

<?php

function InsertFileIntoMongoDB($filename)
{
   error_reporting(E_ALL ^ E_NOTICE);
   require_once 'excel_reader2.php';
   // http://stackoverflow.com/questions/3666412/php-excel-reader-problem-with-utf-8

   // $filename="COOPANS_MERMAID_22032012.xls";
   $xls=new Spreadsheet_Excel_Reader($filename,false,"UTF-8");  // "false" makes it drop formatting and makes the file much smaller
   //$xls->setUTFEncoder('UTF-8');
   //$xls->setUTFEncoder('iconv');
   //$xls->setOutputEncoding('UTF-8');
   //$xls->read("testmermaid.xls");

   $m = new MongoClient();
   $db = $m->testdb;
   $collection = new MongoCollection($db, 'risk_'.GetAdminMemberValue('country'));
   $col2 = new MongoCollection($db, 'TrackPCR');

   $doc=array();
   $arrHeaderKey=array();

   // Get Header names from first row in Excel file
   $row=1;  // first row of excel table
   $NumOfCol=$xls->colcount();
   $NumOfRow=$xls->rowcount();
   for($col=1;$col<=$NumOfCol;$col++) {
      $arrHeaderKey[$col]= iconv("UTF-8","UTF-8//IGNORE",$xls->val($row,$col));  // text
   }

   for($row=2;$row<=$NumOfRow;$row++) {  // skip header row so start by 2
      for($col=1;$col<=$NumOfCol;$col++) {
      
         $cell=iconv("UTF-8","UTF-8//IGNORE",$xls->val($row,$col));  // text
//         $cell=$xls->val($row,$col);  // text
         $doc[$arrHeaderKey[$col]] = $cell;
      }
      $id=trim($doc['CQ Id:']);
      $query = array('PCRID' => $id ,'Variant'=>'a');
      //echo $id." ";
      $cursor = $collection->findone($query);
      $cursor['PCRID']=$id;
      $cursor['Variant']='a';
      $cursor['Mitigation']=trim($doc['Mitigation text connected to PCR:']);
      if($cursor['Mitigation']<>"") {
         echo "Storing: ".$id." ".$cursor['Mitigation']."<br>";
         $collection->save($cursor);
         UpdatePCRInTrackPCRsIfNotExisting($id,$col2);
      }
      $doc=array();
   }

   echo "<br><b>Number of rows analysed: </b>$NumOfRow<br>";
   echo "<b>Number of columns analysed: </b>$NumOfCol<br>";
   echo "<b>Headers detected:</b>";
   for($col=1;$col<=$NumOfCol;$col++) {
      echo '"'.$arrHeaderKey[$col].'"'.", ";
   }
}

// **************************************************
function UpdatePCRInTrackPCRsIfNotExisting($id,$col2)
//  If PCR ($id) does not exist in the TrackPCR list, it must be inserted
//  if a mitigation exist. This function is only called if a mitigation exist.
{
   $Country=GetAdminMemberValue('country');
   $query = array('id' => $id, 'Country' => $Country);
   $cursor = $col2->findone($query);
   if($cursor == NULL)
   {
      echo "<b>$id with Safety Assessment does not exist in TrackPCRs. It is now created!</b><br>";
      $cursor['id']=$id;
      $Headline=GetHeadlineFromCQ($id);
      if($Headline=="") $Headline="-";
      $cursor['Headline']=$Headline;
      $cursor['Status']="Closed";  // mark all as closed
      $cursor['ClosureReason']="SafetyAnalysed";  // mark all as Safety Analysed
      $cursor['Country']=$Country;
      $cursor['Discussion']="Autogenerated during Safety Assessment import - #SA";
      $Log="Auto created during Safety Assessment import. Automatically closed with reason SafetyAnalysed.\n";
      $Log=date("Y-m-d").' '.date("H:i:s").' *** <b>'.$_SESSION['username']."</b>\n".$Log;
      $cursor["Log"]=$Log."\n".$cursor["Log"];
      $cursor["LastUpdate"]=date("Y-m-d").' '.date("H:i:s")." ".$_SESSION['username'];
      $cursor["IRFNum"]="";
      $cursor["ReqRel"]="";
      $cursor["Conclusion"]="";   
      $col2->save($cursor);
   }
}

function GetHeadlineFromCQ($Id)
// returns headline from pcr base. If $Id does not exist, headline in $OldHeadline is returned
{
   $Val=GetKeyFromCQ(array("id"=>$Id),"Headline");
   if($Val=="") return "";
   else return $Val;
}
function GetKeyFromCQ($query,$Key)
{
   $db_name="testdb"; // Database name
   $tbl_name="pcr"; // Collection name
   $m = new MongoClient();
   $db = $m->selectDB($db_name);
   $collection = new MongoCollection($db, $tbl_name);
   $cursor=$collection->findone($query);
   if($cursor==NULL) return "";
   else return $cursor[$Key];
}


// *********** Excel import *****************
function ExcelImport()
{
   // if not started then select file name to be uploaded
   //echo "File Error code: ".$_FILES['userfile']['error'];
   if(isset($_POST['userfile'])) echo "userfile"."<br>";
   if(!isset($_FILES['userfile']['tmp_name'])) {
      ?>
      <!-- The data encoding type, enctype, MUST be specified as below -->
      <form enctype="multipart/form-data" action="risk_view.php" method="POST">
          <!-- MAX_FILE_SIZE must precede the file input field -->
          <input type="hidden" name="MAX_FILE_SIZE" value="60000000" />
          <!-- Name of input element determines name in $_FILES array -->
          JEO's PCR_Safety... file in .xls format (Excel 2003): <input name="userfile" type="file" /><br>
          <input type="submit" value="Upload Mermaid dump" />
      </form>     
      <?php
      echo "<font size=-2>Current PCR_Safety... version=".GetAdminData("PCR_Safety")."</font>";
   }
   else {      
      // In PHP versions earlier than 4.1.0, $HTTP_POST_FILES should be used instead
      // of $_FILES.
      // http://www.php.net/manual/en/features.file-upload.post-method.php
      // make sure uploaddir has chmod a=rwx
      $uploaddir = '/var/www/';
      $uploadfile = $uploaddir . basename($_FILES['userfile']['name']);

      echo '<pre>';
      if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) {
          echo "File is valid, and was successfully uploaded.\n";
      } else {
          echo "Possible file upload attack!\n";
      }

      echo 'Here is some more debugging info:';
      print_r($_FILES);

      print "</pre>";

      // ************************************   
      // Get file into DB
      // ***********************************

      InsertFileIntoMongoDB($_FILES['userfile']['name']);
      // Store filename into DB so version can be shown in admin_main.php
      StoreAdminData('PCR_Safety',$_FILES['userfile']['name']);
   }
}
// **************************************************

function InsertJEOToDB($Id)
{
   ?>
   <form action="risk_view.php" method="post">
   Copy paste (dump) from JEO's PCR_Safety_.. Excel sheet into this area. Do not include header. Individual rows can be included as well as any number of rows:
   <br>
   <textarea name="DumpJEO" COLS=80 ROWS=20></textarea>
   <br>
   <input type="submit" name="JEODump" value="Submit"/>
   </form>
   <?php
   exit;
}

function InsertJEOToDB2($Dump)
{
   $arrRows=explode ("\r\n",$Dump); // get individual rows
   
   foreach($arrRows as $Row)
   {
   
   
      $arrItems=explode ("\t",$Row);  // split on TAB character
      //foreach($arrItems as $Item) echo $Item."<br>";
      
      $assItems['Created']="";
      $assItems['LastTimeUpdated']="";
      
      $arrKeys=array( 'OldPCRno', 'Id', 'Headline', 'State',
                       'CloReason', 'DetRel', 'CorRel',
                       'ElemNature', 'ATMComp', 'Build',
                       'RelatedSWRel', 'SafetySeverity', 'PCRType',
                       'RiskAssessDone', 'MitigationDone', 'Mitigation',
                       'Keyword', 'CommentToPCR', 'RelImplemented');
      $t=0;
      foreach($arrKeys as $k) {
         $assItems[$k]=trim($arrItems[$t++]);
         echo $k." = ".$assItems[$k]."<br>";
      }
    
//      if(strlen($assItems['Id'])>12) {
//         $assItems['Id']=str_replace(" ","",$assItems['Id']);
//         $assItems['Id']=str_replace("\r\n","",$assItems['Id']);
//         $assItems['Variant']="a"; // all are mad 'a' which could be an issue later
//         $assItems['Id']=substr($assItems['PCRID'],0,12);
//      }
//      else $assItems['Variant']="a";
 
     
      // Sanity check of COMP number
      if(substr($assItems['Id'],0,4)<>"COMP" || 
         strlen($assItems['Id'])<>12 ||
         !preg_match ('/^[0-9]{8}$/', substr($assItems['Id'],4,8))
         )
      {
         echo "Incorrect COMP number: ".$assItems['Id'];
         exit;
      }
      if($assItems['Mitigation']<>"") {     
 //        echo $assItems['Id']." ".$assItems['SafetySeverity']." ".$assItems['Mitigation'];
      }             
   }
   exit;
}

function InsertSafetyAssessmentToDB($Id)
{
   ?>
   <form action="risk_view.php" method="post">
   Copy paste (dump) Safety Assessment taken from word into this area:
   <br>
   <textarea name="DumpSafetyAssessment" COLS=80 ROWS=20></textarea>
   <br>
   <input type="submit" name="SADump" value="Submit"/>
   </form>
   <?php
   exit;
}

function InsertSafetyAssessmentToDB2($Dump)
{
   $arrItems=explode ("\t",$Dump);  // split on TAB character
   //foreach($arrItems as $Item) echo $Item."<br>";
   
   $assItems['Created']="";
   $assItems['LastTimeUpdated']="";
   
   $arrKeys=array( 'PCRID', 'FailureMode', 'Hazard', 'Barriers',
                    'EffectPre', 'SeverityPre', 'ProbabilityPre',
                    'RiskPre', 'Mitigation', 'EffectPost',
                    'SeverityPost', 'ProbabilityPost', 'RiskPost',
                    'Approved');
   $t=0;
   foreach($arrKeys as $k) {
      $assItems[$k]=trim($arrItems[$t++]);
   }
 
   if(strlen($assItems['PCRID'])>12) {
      $assItems['PCRID']=str_replace(" ","",$assItems['PCRID']);
      $assItems['PCRID']=str_replace("\r\n","",$assItems['PCRID']);
      $assItems['Variant']=substr($assItems['PCRID'],12,1);
      $assItems['PCRID']=substr($assItems['PCRID'],0,12);
   }
   else $assItems['Variant']="a";
  
   // Sanity check of COMP number
   if(substr($assItems['PCRID'],0,4)<>"COMP" || 
      strlen($assItems['PCRID'])<>12 ||
      !preg_match ('/^[0-9]{8}$/', substr($assItems['PCRID'],4,8))
      )
   {
      echo "Incorrect COMP number: ".$assItems['PCRID'];
      exit;
   }
           
   GenerateSafetyAssessmentForm($assItems,2);               
   
   exit;
}

function GetFromDB($key,$cursor,$DataFrom)
// if DataFrom=1 then data is fetched from the safety assessment database
// if DataFrom=2 then data is taken directly from $cursor that must be associative
{
   if($DataFrom==2) return $cursor[$key];
   $html="";
   // If no record, start record by inserting PCR heading (Subject)
   if($key=='FailureMode') { 
     if(!isset($cursor[$key])) {  // if no failuremode record
        $m = new MongoClient();
        $db = $m->testdb;
        $collection = new MongoCollection($db, 'pcr');
        $query = array('id' => $cursor['PCRID']);
        $cursor2 = $collection->findone($query);
        $html=$cursor2['Headline'];
        goto terminategetfromdb;
     }
   }
   if(isset($cursor[$key])) $html=$cursor[$key];
   else $html="";

terminategetfromdb:
   return $html;
}
?>

<?php
function GenerateSelect($name = '', $options = array(), $nameselection) {
// Generate a table based on the array input. 
// Drop down list gets named: $name
// $options: The key of the array
// $value: The values of the array
// $nameselection: If set it is matched all $value and if it matches, it makes this value the default selection
// http://www.kavoir.com/2009/02/php-drop-down-list.html
   $html = '<select name="'.$name.'">';
   foreach ($options as $option => $value) {
      if ($value==$nameselection) {
         $html .= '<option selected value='.$value.'>'.$value.'</option>';
      }
      else $html .= '<option value='.$value.'>'.$value.'</option>';
   }
   $html .= '</select>';
   return $html;
}

function GetAdminMemberValue($key) {
   $m = new MongoClient();
   $db = $m->admin;
   $collection = new MongoCollection($db, 'members');
   $query = array('user' => $_SESSION["username"]);
   $cursor = $collection->findone($query);
   return ($cursor[$key]);
}

function GenerateSafetyAssessmentForm($cursor,$DataFrom)
// if DataFrom=1 then data is fetched from the safety assessment database
// if DataFrom=2 then data is taken directly from $cursor that must be associative
{
   $Id=GetFromDB('PCRID',$cursor,$DataFrom);
   ?>
   <form action="risk_view.php" method="post">

   <table border="0">
   <tr>
   <!-- make PCR heading  -->
   <td>PCR Id:</td>
   <td><input type="text" name="PCRID" size="25" value="<?php echo $Id;?>" readonly/>
   Variant:<?php echo GenerateSelect("Variant",array("a","b","c","d","e","f","g","h","i","j"), GetFromDB('Variant',$cursor,$DataFrom));?>
   <a href="print.php?id=<?php echo $Id;?>" target="_blank"><?php echo "Lookup-PCR-in-new-tab";?></a>
   </td>
   </tr>
   <tr><td>Created:</td>
   <td><input type="text" name="Created" size="25" value="<?php echo GetFromDB('Created',$cursor,$DataFrom);?>" readonly/>
   </td>
   </tr>
   <tr>
   <td>LastTimeUpdated:</td>
   <td><input type="text" name="LastTimeUpdated" size="25" value="<?php echo GetFromDB('LastTimeUpdated',$cursor,$DataFrom);?>" readonly/>
   </td>
   </tr>
   <tr>
   <td valign="top">Failure Mode:</td>
   <td><textarea name="FailureMode" COLS=80 ROWS=4><?php echo GetFromDB('FailureMode',$cursor,$DataFrom);?></textarea></td>
   </tr>
   <tr>
   <td valign="top">Hazard:</td>
   <td><textarea name="Hazard" COLS=80 ROWS=2><?php echo GetFromDB('Hazard',$cursor,$DataFrom);?></textarea>
   </tr></td>
   <tr>
   <td valign="top">Barriers/ Explanation:</td>
   <td><textarea name="Barriers" COLS=80 ROWS=2><?php echo GetFromDB('Barriers',$cursor,$DataFrom);?></textarea></td>
   </tr>
   <tr>
   <td valign="top">Effect (Pre):</td>
   <td><textarea name="EffectPre" COLS=80 ROWS=2><?php echo GetFromDB('EffectPre',$cursor,$DataFrom);?></textarea></td>
   </tr>
   <tr>
   <td>Pre Mitigation:</td>
   <td>Severity: 
   <?php echo GenerateSelect("SeverityPre",array("","1","2","3","4","5"), GetFromDB('SeverityPre',$cursor,$DataFrom));?>
   &nbsp;&nbsp;Probability:
   <?php echo GenerateSelect("ProbabilityPre",array("","I","II","III","IV","V"), GetFromDB('ProbabilityPre',$cursor,$DataFrom));?>
   &nbsp;&nbsp;Risk:
   <?php echo GenerateSelect("RiskPre",array("","A","B","C","D"), GetFromDB('RiskPre',$cursor,$DataFrom));?>
   </td>
   </tr>

   <tr>
   <td valign="top">Mitigation:</td>
   <td><textarea name="Mitigation" COLS=80 ROWS=2><?php echo GetFromDB('Mitigation',$cursor,$DataFrom);?></textarea></td>
   </tr>
   <tr>
   <td valign="top">Effect (Post):</td>
   <td><textarea name="EffectPost" COLS=80 ROWS=2><?php echo GetFromDB('EffectPost',$cursor,$DataFrom);?></textarea></td>
   </tr>
   <tr>
   <td>Post Mitigation:</td>
   <td>Severity: 
   <?php echo GenerateSelect("SeverityPost",array("","1","2","3","4","5"), GetFromDB('SeverityPost',$cursor,$DataFrom));?>
   &nbsp;&nbsp;Probability:
   <?php echo GenerateSelect("ProbabilityPost",array("","I","II","III","IV","V"), GetFromDB('ProbabilityPost',$cursor,$DataFrom));?>
   &nbsp;&nbsp;Risk:
   <?php echo GenerateSelect("RiskPost",array("","A","B","C","D"), GetFromDB('RiskPost',$cursor,$DataFrom));?>
   </tr>
   <tr>
   <td>Approved:</td>
   <td><input type="text" name="Approved" size="25" value="<?php echo GetFromDB('Approved',$cursor,$DataFrom);?>" readonly/>
   <input type="submit" name="Approve" value="Approve"/>
   </td>
   </tr>
   </table>
   <input type="submit" name="updaterisk" value="Update/Submit Form"/>
   </form>
   <?php
}

if(isset($_POST['pcr'])) {
   $pcrnum=$_POST['pcr'];
   $Variant=$_POST['Variant'];
   $_SESSION["risknumpointer"]=0;   // used to move forward/backward in searches
   $_SESSION["risk_regularid"]=array($pcrnum);
}
elseif(isset($_GET['pcr'])) {
   $pcrnum=$_GET['pcr'];
   $Variant=$_GET['Variant'];
   $_SESSION["risknumpointer"]=0;   // used to move forward/backward in searches
   // if called with only one PCR do not allow to scroll through PCRs
   if(isset($_GET['resetregularid'])) $_SESSION["risk_regularid"]=array($pcrnum);
}
elseif(isset($_GET['insert'])) {
   InsertSafetyAssessmentToDB($_GET['insert']);
}
elseif(isset($_POST['SADump'])) {
   InsertSafetyAssessmentToDB2($_POST['DumpSafetyAssessment']);
}
elseif(isset($_GET['insertJEO']) ||                 // stage 1
       isset($_FILES['userfile']['tmp_name'])) {    // stage 2
   //InsertJEOToDB($_GET['insertJEO']);
   ExcelImport();
   exit;
}

//elseif(isset($_POST['JEODump'])) {
//   InsertJEOToDB2($_POST['DumpJEO']);
//}



// Administrate moving forward and backwards based on outcome of search
if (isset($_POST['riskforward'])) {
   $riskarray=$_SESSION["risk_regularid"];
   $pointer=$_SESSION["risknumpointer"]+1;
   if($pointer>=count($riskarray)) $pointer=0;
   $_SESSION["risknumpointer"]=$pointer;
   $pcrnum=$riskarray[$pointer];
   if($pcrnum=="") exit(0);
}
elseif (isset($_POST['riskbackward'])) {
   $riskarray=$_SESSION["risk_regularid"];
   $pointer=$_SESSION["risknumpointer"]-1;
   if($pointer<0) $pointer=count($riskarray)-1;
   $_SESSION["risknumpointer"]=$pointer;
   $pcrnum=$riskarray[$pointer];
   if($pcrnum=="") exit(0);
}

// Store risk form into DB
if(isset($_POST['updaterisk']) || isset($_POST['Approve'])) {
   $m = new MongoClient();
   $db = $m->testdb;
   $collection = new MongoCollection($db, 'risk_'.GetAdminMemberValue('country'));
   $query = array('PCRID' => $_POST['PCRID'],'Variant'=>$_POST['Variant']);
   $cursor = $collection->findone($query);


   $riskarray=array('PCRID', 'Variant','FailureMode', 'Hazard', 'Barriers',
                    'EffectPre', 'SeverityPre', 'ProbabilityPre', 'RiskPre',
                    'Mitigation', 'EffectPost', 'SeverityPost', 
                    'ProbabilityPost', 'RiskPost', 'Approved', 'Created');
   foreach($riskarray as $i) {
      $cursor[$i]=$_POST[$i];
   }


   // Check id approved and insert "date - time - name" into DB
   if(isset($_POST['Approve'])) {
      $cursor['Approved']=date("Y-m-d").' '.date("H:i:s").' '.$_SESSION['username'];
   }

//var_dump($cursor);
//exit(0);
   if($cursor['Created']=="") $cursor['Created']=date("Y-m-d").' '.date("H:i:s").' '.$_SESSION['username'];
   $cursor['LastTimeUpdated']=date("Y-m-d").' '.date("H:i:s").' '.$_SESSION['username'];
   $collection->save($cursor);
   include("headerline.html");
   echo "Risk information related to PCR ".$_POST['PCRID']." is stored";
   
   echo '<br><br><a href="risk_view?insert">Insert Safety Assessments from Word table to DB</a>';
   exit;
}

$m = new MongoClient();
$db = $m->testdb;
$collection = new MongoCollection($db, 'risk_'.GetAdminMemberValue('country'));
$cursor = $collection->findOne(array('PCRID' => $pcrnum, 'Variant' => $Variant));

// If no risk entry aldready in DB, start bulding one up
if(!isset($cursor['PCRID'])) $cursor=array('PCRID' => $pcrnum);

?>
<!-- ****************************************************** -->
<!--                    Main programme                      -->
<!-- ****************************************************** -->

<?php include("headerline.html"); ?>

<form action="risk_view.php" method="post">
<table border="0">
<!-- row 1 -->
<tr>
<td><font size=+1><b>Safety Assessment form</b></font></td>
<!--<td><input type="text" name="pcrnum" size="5" value="<?php echo $_SESSION['risknum'];?>"/></td>-->
<!--<td><input type="submit" name="irfget" value="Get IRF"/></td>  -->

<td><input type="submit" name="riskbackward" value="<<<"/></td>
<td><input type="submit" name="riskforward" value=">>>"/></td>
</tr>
</table>
</form>

<?php
if(!isset($cursor['PCRID'])) $cursor['PCRID']=$pcrnum;
GenerateSafetyAssessmentForm($cursor,1);
?>

</body>
</html>

